#spring:
#  config:
#    import:
#      - application-google.yml
#      - application-kakao.yml
#      - application-naver.yml
#      - application-rds.yml
#      - application-jwt.yml
#      - application-mail.yml
#
#  # jpa
#  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#
#  flyway:
#    enabled: true # flyway를 사용하겠다는 설정
#    baseline-on-migrate: true # flyway 버전 정보를 flyway_schema_history 라는 테이블에서 관리하는데 해당 테이블을 자동으로 생성해주는 옵션. 기본값은 false로 히스토리 테이블이 이미 존재할 때 사용
#    url: ${RDS_URL}
#    user: ${RDS_USERNAME}
#    password: ${RDS_SECRET}
#
#  #  # 파일 업로드 용량 제한
#  #  servlet:
#  #    multipart:
#  #      max-file-size: 10MB
#  #      max-request-size: 10MB
#
#  # 404 페이지 처리, 404
#  web:
#    resources:
#      add-mappings: false
#
#  #spring security filter log
#  logging:
#    level:
#      org:
#        springframework:
#          security: DEBUG
#
#
## redis, my properties
#redis:
#  network:
#    host: localhost
#    port: 6379
#
#
#images:
#  upload-path: "/home/ec2-user/images/guesthouse/"
#  upload-ec2: "/home/ec2-user"
#  member-profile : "images/memberprofile/"
#  room-dir: "images/room/"
#
#
#log:
#  config:
#    level: TRACE
#    path: "/home/ec2-user/log"
#    log-filename: "main-project-log"
#    err-log-filename: "main-project-log-err"